services:
  backend:
    build: ./app/backend
    ports:
      - "5050:5050" 
    networks:
      - app
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase 
    depends_on:
      - mongodb

  frontend:
    build: ./app/frontend
    ports:
      - "5173:5173"  
    networks:
      - app
    environment:
       REACT_APP_API_URL: http://backend:5050 

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"  
    networks:
      - app
    volumes:
      - mongodb_data:/data/db

networks:
  app:
    driver: bridge 

volumes:
  mongodb_data:
