---
- name: Install Trivy and Docker
  become: true
  hosts: localhost
  tasks:
    - name: Install prerequisite packages
      apt:
        name: 
          - wget
          - apt-transport-https
          - gnupg
          - lsb-release
        update_cache: yes

    - name: Add Trivy GPG key
      apt_key:
        url: https://aquasecurity.github.io/trivy-repo/deb/public.key
        state: present

    - name: Add Trivy repository
      apt_repository:
        repo: deb https://aquasecurity.github.io/trivy-repo/deb {{ ansible_distribution_release }} main
        state: present

    - name: Install Trivy
      apt:
        name: trivy
        update_cache: yes
        
    - name : Install Docker
      command : sudo apt-get install -y docker.io
      become : yes
      become_user : root

    - name : Start Docker Service
      command : sudo systemctl start docker
      become : yes
      become_user : root

    - name: Start trivy
      service:
        name: trivy
        state: started

