---
- name: Install Trivy and Docker
  become: true
  hosts: localhost
  tasks:
    - name: Install prerequisite packages
      apt:
        name: 
          - wget
          - apt-transport-https
          - gnupg
          - lsb-release
        update_cache: yes

    - name: Add Trivy GPG key
      apt_key:
        url: https://aquasecurity.github.io/trivy-repo/deb/public.key
        state: present

    - name: Add Trivy repository
      apt_repository:
        repo: deb https://aquasecurity.github.io/trivy-repo/deb {{ ansible_distribution_release }} main
        state: present

    - name: Install Trivy
      apt:
        name: trivy
        update_cache: yes
        
    - name: Update and upgrade all packages to the latest version
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
